### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by phkrief** [eclipse-opensmartclide/smartclide-Che-REST-Client#1]
Dear @schlotze, @deanone ,

Should we delete this repo?
It is empty

**Comment by deanone** [comment]
@phkrief I believe we can and we should (in order to start reducing the number of repos).

**Comment by schlotze** [comment]
@phkrief @deanone Agree, my idea was to go through the list of repositories in our next Dev-TelCo and make a quick check.

**Comment by deanone** [comment]
@schlotze ok. @phkrief @eclipsewebmaster I guess you can proceed with deleting the repo.
